ALTER TABLE "Job" ADD COLUMN "company" TEXT;
ALTER TABLE "Job" ADD COLUMN "level" TEXT;
ALTER TABLE "Job" ADD COLUMN "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Job" ADD COLUMN "urgent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Job" ADD COLUMN "logo" TEXT;
